baseURL = 'https://epsilon-delta.com'
languageCode = 'es-es'
title = 'Epsilon Delta'
theme = "petheme"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
[markup]
  [markup.goldmark.renderer]
    unsafe = true  # permite HTML en Markdown (necesario para shortcodes rawhtml, etc.)
  [markup.highlight]
    noClasses = false  # mejor si el tema trae CSS para sintaxis

# (Opcional) Taxonomías
[taxonomies]
  tag = "tags"
  category = "categories"