# Este es el único archivo de configuración que Netlify necesita.

[build]
  # El comando que Netlify debe ejecutar para construir tu web.
  command = "hugo"

  # La carpeta que Netlify debe publicar después de construirla.
  publish = "public"

[build.environment]
  # ¡LA LÍNEA MÁS IMPORTANTE!
  # Le decimos a Netlify que use exactamente tu versión de Hugo.
  HUGO_VERSION = "0.149.0"

